# Generated by Django 2.2.4 on 2019-08-02 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час зчитування значення лічильника'),
            preserve_default=False,
        ),
    ]
