# Generated by Django 2.2.4 on 2019-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20190802_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Лічильник', 'verbose_name_plural': 'Лічильники'},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Test'},
        ),
        migrations.AlterField(
            model_name='counter',
            name='identifier',
            field=models.CharField(max_length=30, verbose_name='Показання'),
        ),
    ]
