# Generated by Django 2.2.4 on 2019-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20190803_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name': 'Адреса', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='read_at',
        ),
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.IntegerField(verbose_name='Номер квартиры'),
        ),
    ]
