# Generated by Django 2.2.4 on 2019-08-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20190803_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='hull_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='identifier',
            field=models.CharField(max_length=30, verbose_name='Id'),
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.Address')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владелец',
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.Owners'),
        ),
    ]
