# Generated by Django 2.2.4 on 2019-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20190807_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(default=1, max_length=35, verbose_name='Тарифы')),
            ],
            options={
                'verbose_name': 'Тариф счетчика',
                'verbose_name_plural': 'Тариф счетчика',
            },
        ),
        migrations.AlterField(
            model_name='cityorvillage',
            name='city_village',
            field=models.CharField(default='Город', max_length=35, verbose_name='Место(Город, Село)'),
        ),
        migrations.AlterField(
            model_name='faza',
            name='faza',
            field=models.CharField(default='Однофазный', max_length=35, verbose_name='Количество фаз'),
        ),
        migrations.AddField(
            model_name='counter',
            name='rate',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='readings.Rate'),
            preserve_default=False,
        ),
    ]
