# Generated by Django 2.2.4 on 2019-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_auto_20190807_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Активная +', max_length=35, verbose_name='Типы учета')),
            ],
            options={
                'verbose_name': 'Тип учета',
                'verbose_name_plural': 'Тип учета',
            },
        ),
    ]
