# Generated by Django 2.2.4 on 2019-08-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(default='Население', max_length=35, verbose_name='Типы потребителя')),
            ],
            options={
                'verbose_name': 'Тип потребителей',
                'verbose_name_plural': 'Тип потребителей',
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='type',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='readings.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='readings.Subscriber'),
            preserve_default=False,
        ),
    ]
