# Generated by Django 2.2.4 on 2019-08-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.Address'),
        ),
        migrations.AddField(
            model_name='value',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.Owners'),
        ),
    ]
