# Generated by Django 2.2.4 on 2019-08-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0008_auto_20190807_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.RemoveField(
            model_name='counter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='identifier',
        ),
        migrations.AddField(
            model_name='counter',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='counter',
            name='city',
            field=models.CharField(default=0, max_length=30, verbose_name='Населенный пункт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='counter_id',
            field=models.CharField(default=0, max_length=50, verbose_name='Номер счетчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='house_number',
            field=models.IntegerField(default=0, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Количество знаков'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Коэффициент трансформации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='street',
            field=models.CharField(default=0, max_length=30, verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='verification_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Межпроверочный интервал'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='city_or_village',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='readings.CityOrVillage', verbose_name='Город или Село'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='date_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей верификации'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='faza',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='readings.Faza', verbose_name='Однофазный/Трёхфазный'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='owner',
            field=models.CharField(default=0, max_length=50, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='rate',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='readings.Rate', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='subscriber',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='readings.Subscriber', verbose_name='Абонент'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='type',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='readings.Type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='counter',
            name='region',
            field=models.ForeignKey(default=0, on_delete='DO_NOTHING', to='readings.Region', verbose_name='Область'),
            preserve_default=False,
        ),
    ]
