# Generated by Django 2.2.4 on 2019-08-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0010_auto_20190807_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='readings.Value', verbose_name='Показание')),
            ],
        ),
    ]
