# Generated by Django 2.2.4 on 2019-08-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0011_readings'),
    ]

    operations = [
        migrations.AddField(
            model_name='readings',
            name='subscriber1',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='readings.Counter', verbose_name='Абонент'),
            preserve_default=False,
        ),
    ]
