# Generated by Django 2.2.4 on 2019-08-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0012_readings_subscriber1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readings',
            name='subscriber1',
        ),
        migrations.RemoveField(
            model_name='readings',
            name='value1',
        ),
        migrations.AddField(
            model_name='readings',
            name='counter',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='readings.Counter', verbose_name='Номер счетчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readings',
            name='value',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='readings.Value', verbose_name='Показание'),
            preserve_default=False,
        ),
    ]
