# Generated by Django 2.2.4 on 2019-08-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0013_auto_20190807_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readings',
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('readings.counter',),
        ),
    ]
